const useOurProduct = () => {
  const ourProducts = [
    {
      name: "Home Decor & Living",
      nameKey: "homeDecorLiving",
      slug: "home-decor",
      url: "/our-product/home-decor",
      content: [
        {
          title: "Lampshade",
          description: "lampshade",
          url: "/",
          btnLabel: "LAMPSHADE CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/home-1.png",
          link: "https://drive.google.com/file/d/1rirVDC6M6_cGt8NawCcdLD2enBVoO9IO/view",
        },
        {
          title: "Chair & Bench / Papasan",
          description: "chairBenchPapasan",
          url: "/",
          btnLabel: "CHAIR & BENCH CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/home-2.png",
          link: "https://drive.google.com/file/d/1ddVbXjC6Lcqn1i9mTIiMBKEy_0o6TdKy/view",
        },
        {
          title: "Table",
          description: "table",
          url: "/",
          btnLabel: "TABLE CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/home-3.png",
          link: "https://drive.google.com/file/d/1LowP4bWP-x0ISpo8u6qT3E9nv6Ow5NFn/view",
        },
        {
          title: "Cabinet - Shelf - Mirror",
          description: "cabinetShelfMirror",
          url: "/",
          btnLabel: "CABINET - SHELF - MIRROR CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/home-4.png",
          link: "https://drive.google.com/file/d/1fl4Ik3hbewccMCQgn2RT9twnAGUj44gn/view",
        },
        {
          title: "Pet Bed",
          description: "petBed",
          url: "/",
          btnLabel: "PET BED CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/home-6.png",
          link: "https://drive.google.com/file/d/19AhzDiWGRBA9yYS34GfiqT0WcZJPjkk5/view",
        },
      ],
    },
    {
      name: "Kitchen & Dinning",
      nameKey: "kitchenDinning",
      slug: "kitchen-dinning",
      url: "/our-product/kitchen-dinning",
      content: [
        {
          title: "Tableware ",
          description: "tableware",
          url: "/",
          btnLabel: "TABLEWARE CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/kit-1.png",
          link: "https://drive.google.com/file/d/1lL60pgGJWi4s_3hOCgVqNtuKOsiANyex/view",
        },
        {
          title: "Kitchenware",
          description: "kitchenware",
          url: "/",
          btnLabel: "KITCHENWARE CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/kit-2.png",
          link: "https://drive.google.com/file/d/1-9H3BMKJVBvvFBK2mGFd34mnFyitWNlO/view",
        },
      ],
    },
    {
      name: "Outdoor & Garden",
      nameKey: "outdoorGarden",
      slug: "outdoor-garden",
      url: "/our-product/outdoor-garden",
      content: [
        {
          title: "Picnic Basket",
          description: "picnicBasket",
          url: "/",
          btnLabel: "PICNIC BASKET",
          banner: "https://media.handi-eco.vn/images/product/out-1.png",
          link: "https://drive.google.com/file/d/1K7vTRITSbM9A9FAckD7JF9cYKRwsaw60/view",
        },
        {
          title: "Vase",
          description: "vase",
          url: "/",
          btnLabel: "VASE CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/out-2.png",
          link: "https://drive.google.com/file/d/1K7vTRITSbM9A9FAckD7JF9cYKRwsaw60/view",
        },
        {
          title: "Planter",
          description: "planter",
          url: "/",
          btnLabel: "PLANTER CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/out-3.png",
          link: "https://drive.google.com/file/d/1K7vTRITSbM9A9FAckD7JF9cYKRwsaw60/view",
        },
        {
          title: "Sun lounger",
          description: "sunlounger",
          url: "/",
          btnLabel: "SUN LOUNGER CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/out-4.png",
          link: "https://drive.google.com/file/d/1fSm0clC9o7Achl2GYO7NaMLkERrUvGDh/view",
        },
      ],
    },
    {
      name: "Gift & Fashion Accessories",
      nameKey: "giftFashionAccessories",
      slug: "gift-fashion",
      url: "/our-product/gift-fashion",
      content: [
        {
          title: "Gift Box / Storage Boxes",
          description: "giftboxStorageBoxes",
          url: "/",
          btnLabel: "GIFT BOX CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/gift-1.png",
          link: "https://drive.google.com/file/d/1MQmuSHDRFOB34vM2hqEUWTxf-pmZfbw8/view",
        },
        {
          title: "Fashion Bags",
          description: "fashionBags",
          url: "/",
          btnLabel: "HANDBAG CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/gift-2.png",
          link: "https://drive.google.com/file/d/1Yeqf93r6YJ7ns0wQjH_GReixW9-gdd19/view",
        },
        {
          title: "Handcrafted Jewelry",
          description: "handcraftedJewelry",
          url: "/",
          btnLabel: "HANDCRAFTED JEWELRY CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/gift-3.png",
          link: "https://drive.google.com/file/d/1d4KFLEpe8cvEHuB36j7w5-tJQJURFc6D/view",
        },
      ],
    },
    {
      name: "Bathroom & Laundry",
      nameKey: "bathroomLaundry",
      slug: "bathroom-laundry",
      url: "/our-product/bathroom-laundry",
      content: [
        {
          title: "Laundry Basket",
          description: "laundryBasket",
          url: "/",
          btnLabel: "LAUNDRY BASKET CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/bath-1.png",
          link: "https://drive.google.com/file/d/1MskaZ6yfNvzJcNQ7HXV18e8eHbwuvBWz/view",
        },
        {
          title: "Bath Sponge",
          description: "bathSponge",
          url: "/",
          btnLabel: "BATH SPONGE CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/bath-2.png",
          link: "https://drive.google.com/file/d/1MskaZ6yfNvzJcNQ7HXV18e8eHbwuvBWz/view",
        },
        {
          title: "Soap Holder",
          description: "soapHolder",
          url: "/",
          btnLabel: "SOAP HOLDER CATALOGUE",
          banner: "https://media.handi-eco.vn/images/product/bath-4.png",
          link: "https://drive.google.com/file/d/1MskaZ6yfNvzJcNQ7HXV18e8eHbwuvBWz/view",
          hideLink: true,
        },
      ],
    },
  ];
  return { ourProducts };
};
export default useOurProduct;
