import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import NavBar from "@/app/components/layout/nav-bar";
import Footer from "@/app/components/layout/footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Handi&Co</title>
      </head>
      <body className={` ${inter.className} bg-[#11434C]`}>
        <div className="min-h-screen flex flex-col justify-between  gap-4">
          <NavBar />
          <div className="flex flex-col flex-grow h-full relative w-full">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
